# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [ ]:
# Garcia

import numpy as np

#### 2. Print the numpy version

In [4]:
import numpy as np

print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [20]:
import numpy as np

arr = np.zeros([5])

print(arr)

[0. 0. 0. 0. 0.]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [17]:
import numpy as np

arr = np.zeros([15])
arr[6] = 1

print(arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [211]:
from numpy import random

arr = random.randint(0, 16, (4, 4))

print(arr)

[[14  4  0  8]
 [ 3 15  7  0]
 [ 6  1  0 12]
 [ 2 13  6  7]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [21]:
import numpy as np

arr = np.array([1, 2, 4, 0, 4, 0])

x = np.where(arr > 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [43]:
from numpy import random

arr = random.rand(4, 4, 4)

print(arr)

[[[0.71586323 0.35571273 0.18781153 0.44291041]
  [0.75998109 0.19353718 0.979393   0.686807  ]
  [0.37528048 0.56466756 0.12963661 0.82158148]
  [0.79621129 0.21776255 0.79900173 0.86240859]]

 [[0.03573017 0.95706949 0.39497778 0.65313554]
  [0.11149421 0.2254502  0.70197289 0.40775471]
  [0.69140142 0.31360112 0.5197921  0.75669368]
  [0.22799612 0.5758065  0.91430953 0.63251652]]

 [[0.5019376  0.94563378 0.63385357 0.51360083]
  [0.87761466 0.41881806 0.26494427 0.77997523]
  [0.27730666 0.84429044 0.06394008 0.2659985 ]
  [0.81077205 0.69080754 0.1585531  0.06225316]]

 [[0.10616069 0.94019057 0.08432232 0.43684609]
  [0.71680674 0.73350872 0.60927582 0.47462672]
  [0.42946071 0.59389025 0.9439673  0.886777  ]
  [0.06072565 0.12317068 0.11186621 0.56437689]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [46]:
from numpy import random

arr = random.rand(15, 15)

x = np.min(arr)
y = np.max(arr)

print(arr)

print("Min:", x)
print("Max:", y)

[[0.2189467  0.9727936  0.33994884 0.65632589 0.83959294 0.99645877
  0.93659841 0.27535764 0.37147267 0.56981765 0.59795029 0.84316465
  0.45160804 0.42722175 0.09351776]
 [0.30072033 0.25349682 0.34757941 0.95214684 0.03092571 0.94400858
  0.61556795 0.94759319 0.2735768  0.00476768 0.41804845 0.6868981
  0.57938076 0.60534461 0.15961734]
 [0.43693846 0.21056968 0.09946964 0.56185739 0.24365191 0.0880851
  0.66564882 0.84499572 0.57787221 0.29732614 0.40755903 0.31333327
  0.61448281 0.61882171 0.43922011]
 [0.32176944 0.70288657 0.51049601 0.22302409 0.50979486 0.52664724
  0.76624166 0.09902083 0.91812597 0.06432892 0.68512001 0.67172163
  0.8756088  0.2097748  0.78057411]
 [0.39745703 0.91645209 0.59467017 0.98004798 0.35993018 0.3866761
  0.07111729 0.21912064 0.07389773 0.29854311 0.58992925 0.41894367
  0.66329568 0.23787372 0.03334566]
 [0.53159483 0.57411774 0.3838615  0.64602121 0.28479976 0.57031652
  0.29744646 0.39319816 0.07801391 0.83752052 0.56253387 0.30582425
  0.540

#### 9. Create a random array of size 25 and find the mean value

In [41]:
from numpy import random

arr = random.rand(25)

x = np.mean(arr)

print(arr)
print("Mean:", x)

[0.91938785 0.9008424  0.32591805 0.94797708 0.56949286 0.01528093
 0.49835477 0.15888548 0.71585147 0.72117163 0.03832956 0.29960306
 0.00360618 0.74069801 0.08291275 0.50469994 0.28255257 0.28539326
 0.32396557 0.5207503  0.62336674 0.17787292 0.16296336 0.74454233
 0.16228234]
Mean: 0.4290680564854651


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [57]:
import numpy as np

a = np.array([2, 4, 9])
b = np.array([1, 14, 6])

print(a)
print(b)

[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [59]:
print(a + b)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [52]:
print(a - b)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [54]:
print(a * b)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [55]:
print(a / b)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [60]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [63]:
print(arr[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [86]:
x = np.array(arr[1])

print(x)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [87]:
y = np.array([arr[0, 2], arr[1, 2], arr[2, 2]])

print(y)

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [67]:
z = np.array([[arr[1, 1], arr[1, 2]], [arr[2, 1], arr[2, 2]]])

print(z)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [89]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [ ]:
w = arr[1:3, 1:3]

print(w)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [ ]:
x = arr[0, ::2]

print(x)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [114]:
y = arr[::-1]

print(y)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [116]:
z = arr[:, -2:]

print(z)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [117]:
import numpy as np

arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print(arr1)
print(arr2)

[11  7 33]
[44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [120]:
x = np.concatenate((arr1, arr2))

print(x)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [123]:
y = np.stack((arr1, arr2), axis=0)

print(y)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [124]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [125]:
x = np.vstack((arr1, arr2))

print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [126]:
y = np.hstack((arr1, arr2))

print(y)

[[1 2 5 6]
 [3 4 7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [1]:
import numpy as np
from numpy import random

arr1 = np.arange(10, 29, (2))
arr2 = random.randint(1, 50, (4, 4))
arr3 = np.ones((2, 3, 4))

arrx = arr2.copy()

print(arr1)
print(arr2)
print(arr3)

[10 12 14 16 18 20 22 24 26 28]
[[20 48  6  3]
 [41 23 14 17]
 [22 18 37 11]
 [ 4 47 29 29]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [2]:
newarr = arr1.reshape(2, -1)
print(newarr)

extract = arr2[-2:]
print(extract)

arr2[arr2 % 2 == 0] = -1
print(arr2)

[[10 12 14 16 18]
 [20 22 24 26 28]]
[[22 18 37 11]
 [ 4 47 29 29]]
[[-1 -1 -1  3]
 [41 23 -1 17]
 [-1 -1 37 11]
 [-1 47 29 29]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [3]:
mean = np.mean(arr2)
median = np.median(arr2)
std = np.std(arr2)
print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std)

sum = np.sum(arrx, axis=1)
print("Sum:", sum)

max = np.max(arr2)
index = np.where(arr2 == max)

print("Maximum value:", max)
print("Index:", index)


Mean: 14.375
Median: 7.0
Standard deviation: 16.936923421920522
Sum: [ 77  95  88 109]
Maximum value: 47
Index: (array([3]), array([1]))


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [210]:
from numpy import random

arr = random.rand(10, 10)
print(arr)

min = np.min(arr, axis=0)
print("Minimum value:", min)

indices = np.unravel_index(np.argsort(arr, axis=None)[-5:], arr.shape)
print("Indices:", indices)

[[0.05823305 0.93798064 0.15560409 0.71853716 0.19210662 0.16473546
  0.61019012 0.90141134 0.64851219 0.08756265]
 [0.97031989 0.25829351 0.50690829 0.4201259  0.03927162 0.88122053
  0.70214303 0.27169847 0.25025305 0.4435294 ]
 [0.74074587 0.94177052 0.09941486 0.71257586 0.01822893 0.78147393
  0.11800988 0.06120947 0.49095967 0.89406646]
 [0.2598657  0.82331883 0.17018624 0.73475085 0.6662826  0.56333255
  0.72447311 0.67486601 0.61734897 0.20510486]
 [0.40907753 0.8461631  0.33098283 0.48211288 0.73733738 0.39589804
  0.31355865 0.41919929 0.82221261 0.19286884]
 [0.7991932  0.5642668  0.55709323 0.18064806 0.39452327 0.4286943
  0.31667998 0.23976833 0.40174396 0.5491871 ]
 [0.421894   0.1698579  0.36190403 0.98372357 0.76398785 0.39133185
  0.86989464 0.95178394 0.37765804 0.26778498]
 [0.72815544 0.0835364  0.19940981 0.93225103 0.12263334 0.54579008
  0.28554342 0.87803393 0.65916658 0.59719311]
 [0.95216444 0.81194725 0.72074796 0.68747255 0.03789156 0.38106502
  0.65002584 